spring.application.name=EnjoyHistoryTrip

logging.level.com.ssafy.history=DEBUG

spring.datasource.url=jdbc:mysql://localhost:3306/history_trip?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=com.ssafy.history.board.dto,com.ssafy.history.history.dto,com.ssafy.history.hotplace.dto,com.ssafy.history.news.dto,com.ssafy.history.quiz.dto,com.ssafy.history.region.dto,com.ssafy.history.trip.dto
mybatis.configuration.map-underscore-to-camel-case=true

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs


news.google.rss.max-items=5
news.google.rss.timeout-ms=10000

# 6시간 안에 이미 수집한 뉴스가 있으면 외부 RSS 호출 생략
# 매 요청마다 크롤링하고 싶으면 0
news.google.rss.refresh-hours=6